[wokwi]
version = 1
firmware = '../.pio/build/esp32dev/firmware.bin'
elf = '../.pio/build/esp32dev/firmware.elf'

#[net]
#gateway="ws://localhost:9011"

#[[net.forward]]
#from = "localhost:8080"
#to = "target:80"